book/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [

    path('reviews/', views.review_list, name='review_list'),
    path('book/<slug:book_slug>/review/add/', views.review_create, name='review_create'),
    path('review/<int:pk>/', views.review_detail, name='review_detail'),
    path('review/<int:pk>/edit/', views.review_edit, name='review_edit'),
    path('review/<int:pk>/delete/', views.review_delete, name='review_delete'),
    path('books/', views.book_list, name='book_list'),
    path('book/add/', views.book_create, name='book_create'),
    path('book/<slug:slug>/', views.book_detail, name='book_detail'),
    path('review/add/', views.review_create, name='review_create'),
    path('categories/', views.category_list, name='category_list'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
    path('selections/', views.selection_list, name='selection_list'),
    path('selection/create/', views.create_selection, name='selection_create'),
    path('selection/<int:pk>/', views.selection_detail, name='selection_detail'),
    path('selection/<int:pk>/edit/', views.edit_selection, name='selection_edit'),
    path('selection/<int:pk>/delete/', views.delete_selection, name='selection_delete'),
    path('home/', views.home, name='home'),
    path('homepage/', views.homepage, name='homepage'),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import thread_create, thread_edit, thread_delete, thread_detail, thread_list

app_name = 'forum'  

urlpatterns = [
    path('forum/', thread_list, name='thread_list'), 
    path('forum/create/', thread_create, name='thread_create'),  
    path('forum/<int:thread_id>/delete/', thread_delete, name='thread_delete'),  
    path('forum/<int:thread_id>/edit/', thread_edit, name='thread_edit'),
    path('forum/<int:thread_id>/', thread_detail, name='thread_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libri/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from book import views
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', views.home, name='home'),
    
    path('forum/', include('forum.urls')),
    path('book/', include('book.urls')),
    path('user/', include('user.urls')),
)


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls')),
    ]
    

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class ForumThread(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now) 

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        base_slug = self.slug
        counter = 1
        while ForumThread.objects.filter(slug=self.slug).exists():
            self.slug = f"{base_slug}-{counter}"
            counter += 1

        super().save(*args, **kwargs)


class Comment(models.Model):
        thread = models.ForeignKey(ForumThread, related_name='comments', on_delete=models.CASCADE)
        author = models.ForeignKey(User, on_delete=models.CASCADE)
        content = models.TextField()
        parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')
        
        def __str__(self):
             return self.content

forum/forms.py
from django import forms
from .models import Comment, ForumThread
from django.contrib.contenttypes.models import ContentType


class ForumThreadForm(forms.ModelForm):
    class Meta:
        model = ForumThread
        fields = ['title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


    
    

forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from .models import ForumThread, Comment
from .forms import ForumThreadForm, CommentForm
from django.utils.text import slugify



@login_required
def thread_create(request):
    if request.method == 'POST':
        form = ForumThreadForm(request.POST)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.author = request.user
            slug = slugify(thread.title)
            original_slug = slug
            counter = 1
            while ForumThread.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            thread.slug = slug
            thread.save()
            return redirect('forum:thread_list')  
    else:
        form = ForumThreadForm()
    return render(request, 'forum/thread_create.html', {'form': form})


def thread_list(request):
    threads = ForumThread.objects.all().order_by('-created_at')
    return render(request, 'forum/thread_list.html', {'threads': threads})

@login_required
def thread_detail(request, thread_id):
    thread = get_object_or_404(ForumThread, id=thread_id)
    comments = thread.comments.filter(parent_comment__isnull=True)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            parent_comment_id = request.POST.get('parent_comment')  
            parent_comment = None

            if parent_comment_id: 
                parent_comment = get_object_or_404(Comment, id=parent_comment_id)

        
            Comment.objects.create(
                thread=thread,
                author=request.user,
                content=content,
                parent_comment=parent_comment  
            )
            return redirect('forum:thread_detail', thread_id=thread.id)
    else:
        form = CommentForm()

    return render(request, 'forum/thread_detail.html', {
        'thread': thread,
        'comments': comments,
        'form': form
    })

@login_required
def thread_edit(request, thread_id):
    thread = get_object_or_404(ForumThread, id=thread_id)
    
    if request.method == 'POST':
        form = ForumThreadForm(request.POST, instance=thread)
        if form.is_valid():
            form.save()
            return redirect('forum:thread_detail', thread_id=thread.id)
    else:
        form = ForumThreadForm(instance=thread)
    
    return render(request, 'forum/thread_edit.html', {'form': form, 'thread': thread})

@login_required
def thread_delete(request, thread_id):
    thread = get_object_or_404(ForumThread, id=thread_id)
    if request.user != thread.author:
        return redirect('forum:thread_list')  
    

    thread.delete()
    return redirect('forum:thread_list')



@login_required
def comment_create(request, thread_id):
    thread = get_object_or_404(ForumThread, id=thread_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.thread = thread
            comment.author = request.user
            comment.save()
            return redirect('forum:thread_detail', thread_id=thread.id)
    else:
        form = CommentForm()

    return render(request, 'forum/comment_create.html', {'form': form})



@login_required
def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user != comment.author:
        return redirect('forum:thread_detail', thread_id=comment.thread.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('forum:thread_detail', thread_id=comment.thread.id)
    else:
        form = CommentForm(instance=comment)

    return render(request, 'forum/comment_edit.html', {'form': form})


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user != comment.author:
        return redirect('forum:thread_detail', thread_id=comment.thread.id)

    comment.delete()
    return redirect('forum:thread_detail', thread_id=comment.thread.id)

forum/templates/forum/thread_create.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% trans "Створити нову гілку форуму" %}
    </title>

    <link rel="stylesheet" href="{% static 'forum/styles.css' %}">
</head>
<body>
    <div class="container">
        <header>
            <h1>
                {% trans "Створити нову гілку форуму" %}
            </h1>

            <li>
                <a href="{% url 'forum:thread_list' %}">
                    {% trans "Форум" %}
                    <span class="underline"></span>
                </a>
            </li>
        </header>

        <div class="form-container">
            <form method="POST">
                {% csrf_token %}

                {{ form.as_p }}

                <button type="submit">
                    {% trans "Створити гілку" %}
                </button>
            </form>
        </div>
    </div>
</body>
</html>

forum/templates/forum/thread_detail.html
{% load i18n %}

<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ thread.title }}</title>
</head>
<body>
    <div class="container">
        <div class="thread-details">
            <h1>{{ thread.title }}</h1>

            <p>{{ thread.content }}</p>

            <p>
                <strong>{% trans "Автор" %}</strong>
                {{ thread.author.username }}
                {% trans "від" %}
                {{ thread.created_at }}
            </p>

            {% if thread.author == user %}
                <a href="{% url 'forum:thread_edit' thread.id %}">
                    {% trans "Редагувати" %}
                </a>
            {% endif %}
        </div>

        <div id="comments-section">
            {% for comment in comments %}
                <div class="comment-item" id="comment-{{ comment.id }}">
                    <div class="comment-header">
                        <p>
                            <strong>{{ comment.author.username }}</strong>
                            {% trans "прокоментував(ла)" %}
                            {{ comment.created_at }}
                        </p>
                    </div>

                    <div class="comment-body">
                        <p>{{ comment.content }}</p>
                    </div>

                    <div class="reply-section">
                        {% for reply in comment.replies.all %}
                            <div class="reply-item" id="reply-{{ reply.id }}">
                                <p>
                                    <strong>{{ reply.author.username }}</strong>
                                    {% trans "відповів(ла)" %}
                                    {{ reply.created_at }}
                                </p>
                                <p>{{ reply.content }}</p>
                            </div>
                        {% endfor %}

                        <form method="POST"
                              class="reply-form"
                              data-parent-comment-id="{{ comment.id }}">
                            {% csrf_token %}

                            <textarea name="content"
                                      placeholder="{% trans 'Напишіть відповідь…' %}"></textarea>

                            <input type="hidden"
                                   name="parent_comment"
                                   value="{{ comment.id }}">

                            <button type="submit">
                                {% trans "Відповісти" %}
                            </button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>

        <form method="POST" class="add-comment-form">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                {% trans "Додати коментар" %}
            </button>
        </form>
    </div>
</body>
</html>

forum/templates/forum/thread_edit.html
{% load i18n %}

<h1>
    {% trans "Редагувати гілку" %}: {{ thread.title }}
</h1>

<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">
        {% trans "Зберегти" %}
    </button>
</form>

<br>

<a href="{% url 'forum:thread_detail' thread.id %}">
    {% trans "Назад" %}
</a>

forum/templates/forum/thread_list.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% trans "Гілки форуму" %}</title>

    <link rel="stylesheet" href="{% static 'forum/styles.css' %}">
</head>
<body>
    <div class="container">
        <header>
            <h1>{% trans "Гілки форуму" %}</h1>

            <a href="{% url 'forum:thread_create' %}" class="create-thread-btn">
                {% trans "Створити нову гілку" %}
            </a>
        </header>

        <div class="thread-list">
            {% if threads %}
                {% for thread in threads %}
                    <div class="thread-card">
                        <h2>
                            <a href="{% url 'forum:thread_detail' thread.id %}">
                                {{ thread.title }}
                            </a>
                        </h2>

                        <p>
                            <strong>{% trans "Створено" %}:</strong>
                            {{ thread.author }}
                            {% trans "від" %}
                            {{ thread.created_at|date:"d M Y H:i" }}
                        </p>

                        <p>
                            {{ thread.content|truncatewords:20 }}
                        </p>
                    </div>
                {% endfor %}
            {% else %}
                <p>
                    {% trans "На форумі немає гілок." %}
                    <a href="{% url 'forum:thread_create' %}">
                        {% trans "Створіть першу гілку!" %}
                    </a>
                </p>
            {% endif %}
        </div>
    </div>
</body>
</html>